### ISSUE TITLE
Few notes

### ISSUE THREAD

**Issue by scandella** [wayborne/craft-dynamic-meta-images#3]
Congrats on your plugin. Great idea. It could be beneficial.

Few notes:

> When enabling the plugin a new folder is created in your template root folder with the name _dynamic-meta-images. Inside of it will also be a demo template demo.twig showcasing some techniques.

No '_dynamic-meta-images' folder was created.

> Enable/disable the image generation per section and per site 

Could not find this option in the plugin settings.

> Make sure that: Puppeteer is installed

How can I check that?
is it: `npm list -g --depth=0`?

> You can find some examples in the plugin directory: src/templates/examples/ 

HTML open tag is missing from the '1.twig' file example

**Comment by jan-dh** [comment]
Thanks for the input! 

> No '_dynamic-meta-images' folder was created.

The idea at first was indeed to automatically create the folder but decided to not take that route. Will update the docs.

>Could not find this option in the plugin settings.

There is no explicit option for that. If you leave the template blank for a section it will not create dynamic images for that section. This is how you enable/disable image generation per section.

>How can I check that?
is it: npm list -g --depth=0?

Puppeteer needs to be installed as a dependency at the root of your project. It should be listed in the dependencies in your package.json

> How can I check that?

You can run `npm list puppeteer` in your project root. This should list Puppeteers. An other way is to check your `package.json` file, make sure it's listed there as a dependency and make sure you've run `npm install`.

> HTML open tag is missing from the '1.twig' file example

Thanks for the catch!

Will update the docs with this info, very valuable input, thanks!
