### ISSUE TITLE
Possible locale issue

### ISSUE THREAD

**Issue by scandella** [wayborne/craft-dynamic-meta-images#4]
I love your plugin.
I've noticed a strange behavior with some date and time objects:
When displaying a string coming from a date field in the browser, the content is formatted with the Craft locale (FR in my case), but when the same content is generated via Dynamic image, the content is in US format.
Do we have to pass a locale for the Puppeteer browser?

**Comment by jan-dh** [comment]
Haven't run into this specific case so will investigate. The "quick" fix would be to explicitly pass the locale or timezone to the date filter in twig as mentioned in the [official docs](https://craftcms.com/docs/5.x/reference/twig/filters.html#arguments):

```
locale
The current application locale will be used by default. If you want to format the date for a different locale, use the locale argument:

{{ entry.postDate|date('short', locale='en-GB') }}
{# Output: 19/1/2038 #}

timezone
You can customize the timezone the time is output in, using the timezone param:

{{ entry.postDate|date('Y-m-d H:i', timezone='UTC') }}
{# Output: 2038-01-19 03:14 #}
Pass false to prevent the date from being converted to the system’s timezone:

{{ entry.customDateFieldWithTimezone|date('Y-m-d H:i', timezone=false) }}
{# Output: 2038-01-18 19:14 #}
```

**Comment by scandella** [comment]
Yes, I've tried this, but the issue remains the same.

**Comment by jan-dh** [comment]
Okido, will investigate

**Comment by jan-dh** [comment]
I've been trying to reproduce but so far unable to; can you provide me with a template you are struggling with?
If I for example take an entry with a postdate of: `5/8/2024 - 2:03 PM` with the CMS set to CEST, I can do:

`{{ entry.postDate|date('d-M-Y: m h')}}`: outputs `08-May-2024 - 2:03 PM`
`{{ entry.postDate|date('d-M-Y: m h', timezone='UTC')}}`: outputs `08-May-2024 12:03` which is a correct conversion according to the timezone converter.

**Comment by scandella** [comment]
Thanks for your test.
The problem is obvious when you use the 'long' date format: months appears in my locale (FR) in the local site, but they are in English in the meta image file. 
Anyway, I've tried the `'long', locale='fr-FR'` syntax, and now it works…  Previously I was using the syntax found in the Twig doc: `locale: 'fr'` which does not seems correct.
Before that, I've been trying without success to pass the locale in your ImageService file using:
`->setOption('args', ['--disable-web-security','--lang=fr-FR'])`

So you can close the ticket.
Thanks for your help.

**Comment by jan-dh** [comment]
Happy you got it working!
