### ISSUE TITLE
Linux install

### ISSUE THREAD

**Issue by scandella** [wayborne/craft-dynamic-meta-images#5]
In our documentation, you might want to add some clue for Linux users when they install  Puppeteer because it seems it won't work out of the box.
In my Debian server, I had to install some extra library with: the following
sudo apt install -y libdrm2 libgbm1 libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 libdrm-common

Keep up the good work.

**Comment by jan-dh** [comment]
Alright, thanks for the feedback; no Linux experience but will add this to the docs 👍

**Comment by jan-dh** [comment]
Added to the docs
